#!/usr/bin/env python3
"""regen-index.py <folder> — regenerate a derived index.md from page frontmatter.

Mechanical half of index regeneration (ingest step 7 / lint check 9):
  - refuses to touch an authored bundle hub (index.md carrying page
    frontmatter: type/title/status) — hub law: wiki/projects/README.md;
  - preserves the existing index's section headers and each page's section
    assignment (section slotting is the agent's judgment, and the user may
    re-slot freely — those choices stick);
  - new pages land under "# New (uncategorized)" and are printed so the
    agent slots them; entries for deleted pages are dropped and printed;
  - nested bundles appear as one entry per bundle — the authored hub
    (<sub>/index.md, same frontmatter test as the guard), titled and
    described from the hub's own frontmatter; satellites are reachable
    through the hub, never listed here (amendment, 2026-07-31).

Exit codes: 0 regenerated · 1 usage/error · 2 refused (authored hub)
"""
import datetime
import re
import sys
from pathlib import Path

ENTRY_RE = re.compile(r"^\*\s+\[(?P<title>.*?)\]\((?P<path>[^)]+)\)(?:\s+-\s+(?P<desc>.*))?\s*$")
EXCLUDE = {"index.md", "README.md", "log.md"}
NEW_SECTION = "New (uncategorized)"


def read_frontmatter(path: Path) -> dict:
    try:
        text = path.read_text(encoding="utf-8")
    except Exception:
        return {}
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end == -1:
        return {}
    block = text[3:end]
    fm = {}
    for line in block.splitlines():
        m = re.match(r"^([A-Za-z_][A-Za-z0-9_]*):\s*(.*)$", line)
        if m:
            val = m.group(2).strip()
            if len(val) >= 2 and val[0] == val[-1] and val[0] in "\"'":
                val = val[1:-1]
            fm[m.group(1)] = val
    return fm


def stamp() -> str:
    now = datetime.datetime.now()
    # Matches the vault's existing derived-index stamp format.
    return f"{now:%Y-%m-%d} {now:%a}, {now:%b} {now.day} — {now:%-I:%M %p}"


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: regen-index.py <folder>", file=sys.stderr)
        return 1
    folder = Path(sys.argv[1]).resolve()
    if not folder.is_dir():
        print(f"ERROR: not a folder: {folder}", file=sys.stderr)
        return 1
    index = folder / "index.md"

    # Hub guard: page frontmatter means authored hub, never a derived listing.
    if index.exists():
        fm = read_frontmatter(index)
        if "type" in fm or "status" in fm:
            print(f"REFUSED: {index} carries page frontmatter ({', '.join(sorted(set(fm) & {'type','title','status'}))}) — "
                  "authored bundle hub, never regenerated (hub law: wiki/projects/README.md).")
            return 2

    # Parse existing index: title line, section order, path -> section.
    h1 = f"# {folder.name.capitalize()}"
    sections: list[str] = []
    assignment: dict[str, str] = {}
    flat = True
    if index.exists():
        current = None
        seen_h1 = False
        for line in index.read_text(encoding="utf-8").splitlines():
            if line.startswith("# "):
                if not seen_h1:
                    h1 = line.rstrip()
                    seen_h1 = True
                else:
                    flat = False
                    current = line[2:].strip()
                    if current not in sections:
                        sections.append(current)
                continue
            m = ENTRY_RE.match(line)
            if m:
                assignment[m.group("path")] = current or ""

    # Scan folder pages.
    pages = sorted(p for p in folder.iterdir()
                   if p.suffix == ".md" and p.name not in EXCLUDE and p.is_file())
    entries = {}
    for p in pages:
        fm = read_frontmatter(p)
        title = fm.get("title") or p.stem.replace("-", " ")
        desc = fm.get("description", "").strip()
        entries[p.name] = f"* [{title}]({p.name})" + (f" - {desc}" if desc else "")

    # Nested bundles: one entry per authored hub (same test as the guard).
    for sub in sorted(p for p in folder.iterdir() if p.is_dir()):
        hub = sub / "index.md"
        fm = read_frontmatter(hub) if hub.exists() else {}
        if "type" in fm or "status" in fm:
            rel = f"{sub.name}/index.md"
            title = fm.get("title") or sub.name.replace("-", " ")
            desc = fm.get("description", "").strip()
            entries[rel] = f"* [{title}]({rel})" + (f" - {desc}" if desc else "")

    new = [n for n in entries if n not in assignment]
    gone = [n for n in assignment if n not in entries]

    out = ["---", f"updated: {stamp()}", "---", h1, "",
           "Derived listing — regenerated by the pipeline, never hand-maintained.", ""]
    if flat:
        out += [entries[n] for n in sorted(entries)]
    else:
        for sec in sections:
            members = [n for n, s in assignment.items() if s == sec and n in entries]
            if not members and not any(assignment[g] == sec for g in gone):
                continue
            if members:
                out += [f"# {sec}", ""]
                out += [entries[n] for n in members]
                out += [""]
        if new:
            out += [f"# {NEW_SECTION}", ""]
            out += [entries[n] for n in sorted(new)]
            out += [""]
    index.write_text("\n".join(out).rstrip() + "\n", encoding="utf-8")

    print(f"REGENERATED: {index} ({len(entries)} entries)")
    if new:
        print("NEW (slot these into sections, or leave flat):")
        for n in sorted(new):
            print(f"  {n}")
    if gone:
        print("DROPPED (files no longer present):")
        for n in sorted(gone):
            print(f"  {n}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
